name: Check Black Formatting

on: [pull_request]

jobs:
  check-format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check formatting with Black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
